service: aws-node-simple-http-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  orderRequest:
    handler: handler.endpoint
    events:
      - http:
          path: order
          method: post
